name: Daily Green Square

on:
  schedule:
    # Runs at 09:00 UTC, Monday–Friday
    - cron: "0 9 * * 1-5"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  poke:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.DEFAULT_BRANCH }}

      - name: Configure Git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "chore: weekday tick $(date -u +'%Y-%m-%d')"

      - name: Push
        run: |
          git push origin ${{ env.DEFAULT_BRANCH }}
